FROM debian:bookworm-slim AS builder

ARG CARGO_TARGET_DIR="target"
ARG CARGO_BUILD_TARGET="."

COPY ./$CARGO_TARGET_DIR/$CARGO_BUILD_TARGET/debian/quicmop-collector_*_*.deb .

RUN dpkg -i ./quicmop-collector_*_*.deb

FROM debian:bookworm-slim

COPY --from=builder /usr/bin/quicmop-collector /usr/bin/quicmop-collector

# Smoke test
RUN ["quicmop-collector", "--version"]

ENTRYPOINT ["/usr/bin/quicmop-collector"]
