FROM debian:bookworm-slim AS builder

ARG CARGO_TARGET_DIR="target"
ARG CARGO_BUILD_TARGET="."

COPY ./$CARGO_TARGET_DIR/$CARGO_BUILD_TARGET/debian/quicmop-kernel-agent_*_*.deb .

RUN dpkg -i ./quicmop-kernel-agent_*_*.deb

FROM debian:bookworm-slim

COPY --from=builder /usr/bin/quicmop-kernel-agent /usr/bin/quicmop-kernel-agent

# Smoke test
RUN ["quicmop-kernel-agent", "--version"]

ENTRYPOINT ["/usr/bin/quicmop-kernel-agent"]
