FROM alpine:3.21

ARG CARGO_TARGET_DIR="target"
ARG CARGO_BUILD_TARGET="."

COPY ./$CARGO_TARGET_DIR/$CARGO_BUILD_TARGET/release/quicmop-qlog-agent /usr/local/bin/quicmop-qlog-agent

# Smoke test
RUN ["quicmop-qlog-agent", "--version"]

ENTRYPOINT ["/usr/local/bin/quicmop-qlog-agent"]
